# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Minecraft installation tasks
  tags:
    - setup-all
    - setup-minecraft
    - install-all
    - install-minecraft
  block:
    - name: Validate Minecraft configuration
      when: minecraft_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Minecraft
      when: minecraft_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"


- name: Perform Minecraft uninstallation tasks
  tags:
    - setup-all
    - setup-minecraft
  block:
    - name: Uninstall Minecraft
      when: not minecraft_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
