# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 XHawk87
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required Minecraft settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - minecraft_identifier
    - minecraft_uid
    - minecraft_gid
    - minecraft_container_network

- name: Validate Minecraft security settings
  ansible.builtin.assert:
    that:
      - minecraft_security_mode == 'insecure' or
        (minecraft_security_privileged | bool == false and
         minecraft_security_write_access | bool == false and
         minecraft_security_allow_capabilities | length == 0)
    fail_msg: >
      Before changing any of the `minecraft_security_` settings, please read
      the section on Security Settings in defaults/main.yml of the role, and
      set `minecraft_security_mode` to `insecure` to acknowledge the risks.
